### PR TITLE
docs: add contributors to readme

### PR DESCRIPTION
**Pull request by alextilot**
### Description of changes
- Add Contributions to the README.md 

### Additional context
- Example command: `@all-contributors please add @<username> for <contributions>`
- @all-contributors please add @alextilot for documentation

### CODE REVIEW

**Review by keyserj — APPROVED** [review]
Ayyy wow this seems really easy, nice. I think we'll have to test it after this is merged
spotlight

**Comment by alextilot** [comment]
@all-contributors please add @alextilot for documentation

**Comment by keyserj** [comment]
@all-contributors
please add @keyserj for code, design, ideas, question, review
please add @CatGuardian for design, projectManagement, ideas
please add @alextilot for a11y, code, design

**Comment by keyserj** [comment]
@all-contributors
 please add @CatGuardian for design, projectManagement, ideas

**Comment by keyserj** [comment]
@all-contributors please add @CatGuardian for design, projectManagement, ideas

**Comment by keyserj** [comment]
@all-contributors please add @alextilot for a11y, code, design

**Comment by keyserj** [comment]
@all-contributors please add @alextilot for a11y, code, design

**Pull request merged**
